monolog:
  channels: ['shipping_export']
  handlers:
    shipping_export:
      type: rotating_file
      path: '%kernel.logs_dir%/%kernel.environment%_shipping_export.log'
      max_files: 14
      level: debug
      channels: ['shipping_export']